give @s kf:onigiri
give @s kf:pinkbeet
give @s kf:eggs
give @s kf:avocado
give @s kf:lapislazulisoup
give @s kf:redstonesoup
give @s kf:diamondsoup
give @s kf:goldensoup
give @s kf:emeraldsoup
give @s kf:chocolatebar
give @s kf:redstonepopsicle
give @s kf:pittedavocado
give @s kf:goldenpopsicle
give @s kf:diamondlollipop
give @s kf:goldenlollipop
give @s kf:redstonelollipop
give @s kf:chocolatelollipop
give @s kf:emeraldlollipop
give @s kf:diamondpopsicle
give @s kf:seaweedorigini
give @s kf:greencoconot
give @s kf:seaweedpopsicle
give @s kf:chocolatepopsicle
give @s kf:greentea
give @s kf:pear
give @s kf:applejuice
give @s kf:obsidianjuice
give @s kf:coconot
give @s kf:redstonejuice
give @s kf:partofthecoconot
give @s kf:obsidiandrink
give @s kf:redstonedrink
give @s kf:strawberryicecream
give @s kf:diamondjuice
give @s kf:diamonddrink
give @s kf:goldenjuice
give @s kf:lifepotion
give @s kf:redstoneicecream
give @s kf:greenteaicecream
give @s kf:diamondicecream
give @s kf:biodegradablestraw
give @s kf:milkshake
give @s kf:icecreamcone
give @s kf:chocolatewithbiscuit
give @s kf:emeraldfish
give @s kf:strawberrymilksha
give @s kf:diamondmilkshake
give @s kf:candyredstonefish
give @s kf:goldenonskewer
give @s kf:redstoneonskewer
give @s kf:goldenicecream
give @s kf:coppericecream
give @s kf:strawberrycookie
give @s kf:redstonethinpopsicle
give @s kf:strawberrythinpopsicle
give @s kf:redstonemilkshake
give @s kf:emeraldthinpopsicle
give @s kf:ricepot
give @s kf:candygoldenfish
give @s kf:goldenmilkshake
give @s kf:emeraldonskewer
give @s kf:poisonedapple
give @s kf:witchcereal
give @s kf:pumpkindonut
give @s kf:spidereyesoup
give @s kf:pumpkinskewer
give @s kf:icecreamblue
give @s kf:vegetablessoup
give @s kf:blueonskewer
give @s kf:pumpkincupcake
give @s kf:bluemilkshake
give @s kf:grapethinpopsicle
give @s kf:emeraldpopsicle
give @s kf:frenchfries
give @s kf:lapislazulilollipop
give @s kf:candydiamondfish
give @s kf:candychocolatefish
give @s kf:candylapisfish
give @s kf:goldenthinpopsicle
give @s kf:chocolatethinpopsicle
give @s kf:goldendrink
give @s kf:chocolatedrink
give @s kf:emeralddrink
